name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Source Code
        run: unzip clinch.zip

      - name: Move files to Root
        # This moves files out of the unzipped folder so the builder can see them
        run: |
          if [ -d "clinch" ]; then
            mv clinch/* .
          fi

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Node Dependencies
        run: npm install

      - name: Make Gradle Executable
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clinch-apk
          path: "**/*.apk"
